:proj-name: Zelda Save Tool
:proj-handle: ZeldaSaveTool
:proj-desc: OoT PC Port Save Converter
:proj-logo: ./Logo.svg
:proj-repo: xoascf/{proj-handle}
:!showtitle:
:icons: font
:!toc-title:
:uri-gh: https://github.com
:uri-repo: {uri-gh}/{proj-repo}
:uri-licence: {uri-repo}/blob/master/LICENSE
:uri-ci: {uri-repo}/actions/workflows/build.yml
:uri-shields: https://img.shields.io
:img-licence-badge: {uri-shields}/github/license/{proj-repo}.svg?label=Licence
:img-ci-badge: {uri-shields}/github/actions/workflow/status/{proj-repo}/build.yml?label=Build

= {proj-name}

ifdef::env-github[]
[subs=attributes+]
++++
<div align="center">
   <a href="{uri-repo}"> <img src="{proj-logo}" width="256" height="256"></a>
   <h1>{proj-name}</h1>
   <h3>{proj-desc}</h3>
   <br />
</div>
<p align="center">
  <a href="{uri-licence}">
    <img src="{img-licence-badge}" />
  </a>
  <a href="{uri-ci}">
    <img src="{img-ci-badge}" />
  </a>
</p>
++++
endif::[]

ifndef::env-github[]
image::{proj-logo}[{proj-name}, align=center, link="{uri-repo}"]

[.text-center]
[.lead]
*{proj-name}*

[.text-center]
{proj-desc}

[.text-center]
image:{img-licence-badge}[Licence, align=center, link="{uri-licence}"]
image:{img-ci-badge}[Build Status (GitHub Actions), align=center, link="{uri-ci}"]
endif::[]

Drop your save file into the program window and specify where to save the converted file.

== How it works
{proj-name} determines the byte order of the save file, corrects the name so that it can be exported for NTSC or PAL and converts it to the specified format for the PC Port, emulator, etc.

== Notes
This program is still experimental, and may not keep some items or progress of certain dungeons when converting saves, please report any related problems by {uri-repo}/issues/new/choose[submitting an issue^].

.Supported formats:
* Emulator save files (*.sra) from any version of the NTSC and PAL releases of the original game.
* PC Port save files (*.sav) for {uri-gh}/blawar/ooot[Open Ocarina^] (oot.sav) and {uri-gh}/HarbourMasters/Shipwright[Ship of Harkinian^] (oot_save.sav).

== Requirements
*.NET 6.0.18*: https://dotnet.microsoft.com/download/dotnet/6.0/runtime
