:proj-name: Zelda Save Tool
:proj-handle: ZeldaSaveTool
:proj-desc: OoT PC Port Save Converter
:proj-logo: ./Logo.svg
:proj-repo: xoascf/{proj-handle}
:!showtitle:
:icons: font
:!toc-title:
:uri-gh: https://github.com
:uri-repo: {uri-gh}/{proj-repo}
:uri-licence: {uri-repo}/blob/master/LICENSE
:uri-ci: {uri-repo}/actions/workflows/build.yml
:uri-shields: https://img.shields.io
:img-licence-badge: {uri-shields}/github/license/{proj-repo}.svg?label=Licence
:img-ci-badge: {uri-shields}/github/actions/workflow/status/{proj-repo}/build.yml?label=Build

= {proj-name}

ifdef::env-github[]
[subs=attributes+]
++++
<div align="center">
   <a href="{uri-repo}"> <img src="{proj-logo}" width="256" height="256"></a>
   <h1>{proj-name}</h1>
   <h3>{proj-desc}</h3>
   <br />
</div>
<p align="center">
  <a href="{uri-licence}">
    <img src="{img-licence-badge}" />
  </a>
  <a href="{uri-ci}">
    <img src="{img-ci-badge}" />
  </a>
</p>
++++
endif::[]

ifndef::env-github[]
image::{proj-logo}[{proj-name}, align=center, link="{uri-repo}"]

[.text-center]
[.lead]
*{proj-name}*

[.text-center]
{proj-desc}

[.text-center]
image:{img-licence-badge}[Licence, align=center, link="{uri-licence}"]
image:{img-ci-badge}[Build Status (GitHub Actions), align=center, link="{uri-ci}"]
endif::[]

== Download
There is no public release yet, but you can download the latest builds via https://nightly.link/xoascf/ZeldaSaveTool/workflows/build/master?preview[nightly.link^].

== Requirements
*.NET 8.0*: https://dotnet.microsoft.com/download/dotnet/8.0/runtime

== Usage
Drop your save file into the program window, choose your target format, and specify where to save the converted file. The program will automatically detect your input format!

== Import Supported Formats
* Emulator save files (`*.sra`) from any version of the NTSC and PAL releases of the original game.
* PC Port save files (`*.sav`, `file*.sav`) for {uri-gh}/blawar/ooot[Open Ocarina^] (`oot.sav`) and {uri-gh}/HarbourMasters/Shipwright[Ship of Harkinian^] (binary `oot_save.sav` and JSON format).
* Dolphin save files (`*.gci`).
* RetroArch and other Libretro SaveRAM files (`*.srm`, `*.SaveRAM`).
* Mupen64Plus and Mupen64Plus FZ saves and states (`*.m64p`, `*.st*`, `*.v2.sav`).
* Project64 save states (`*.pj`).
* Compressed save files and states (`*.zip`, `*.pj.zip`).
* 3DS save files (`*.bin`).

== Export Supported Formats
* PC port `.sav` (binary for OOOT and SoH first two versions; newer versions will automatically convert it to JSON).
* N64 emulator save format (Little Endian).
* N64 console save format (Big Endian).

== Notes
This program is still experimental, and may not keep some items or progress of certain dungeons when converting saves, please report any related problems by {uri-repo}/issues/new/choose[submitting an issue^].

* *Ship of Harkinian*: Save the converted file directly to the game's root directory (where `soh.exe` is located) as `oot_save.sav`. Do NOT save it in the saves folder as `file1.sav` or `global.sav`. The game will automatically update it to its newer JSON format upon loading.
* *3DS Saves*: When converting from 3DS save files (`*.bin`), the death count is not preserved (it is replaced by the save count).
* *Regions*: Select the correct region matching the ROM used (for the console itself, emulators or the PC Port), otherwise Japanese characters or squares may appear in player names.

== How it works
{proj-name} determines the byte order of the save file, corrects the name so that it can be exported for NTSC or PAL and converts it to the specified format for the PC Port, emulator, etc.
