using System.Reflection;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("48e8a78a-d994-4fc3-8640-82a75ee99787")]
[assembly: AssemblyTitle(PName)]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct(PName)]
[assembly: AssemblyVersion(Ver)]
[assembly: AssemblyFileVersion(Ver)]
[assembly: AssemblyInformationalVersion(PVer)]
