//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeldaSaveTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeldaSaveTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDEmpty {
            get {
                object obj = ResourceManager.GetObject("DDEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDFull {
            get {
                object obj = ResourceManager.GetObject("DDFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDHalf {
            get {
                object obj = ResourceManager.GetObject("DDHalf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDOneQuarter {
            get {
                object obj = ResourceManager.GetObject("DDOneQuarter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DDThreeQuarter {
            get {
                object obj = ResourceManager.GetObject("DDThreeQuarter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zelda Save Tool Translation File - Deutsch]
        ///Title=OoT Savegame-Konverter
        ///Drop_It=Legen Sie Ihre Speicherdatei hier ab
        ///Supported=Unterstützte Formate: {0}
        ///Version=Version {0}
        ///Open_First=Öffne zuerst eine Spielstandsdatei!
        ///Supported_Filter=Alle unterstützten Dateien|*.sra;*.sav;*.gci
        ///SRA_Filter=SRA-Dateien (*.sra)|*.sra
        ///PC_Filter=PC-Port-Speicherdateien (*.sav)|*.sav
        ///GCI_Filter=GCI-Dateien (*.gci)|*.gci
        ///All_Filter=Alle Dateien (*.*)|*.*
        ///Save_As_Title=Speichere konvertiert &quot;{0}&quot; als
        ///I=Information
        ///W=Warnung
        ///E= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zelda Save Tool Translation File - English]
        ///Title=OoT Save Converter
        ///Drop_It=Drop your save file here
        ///Supported=Supported formats: {0}
        ///Version=Version {0}
        ///Open_First=Open a save file first!
        ///Supported_Filter=All Supported Files|*.sra;*.sav;*.gci
        ///SRA_Filter=SRA Files (*.sra)|*.sra
        ///PC_Filter=PC Port Save Files (*.sav)|*.sav
        ///GCI_Filter=GCI Files (*.gci)|*.gci
        ///All_Filter=All Files (*.*)|*.*
        ///Save_As_Title=Save converted &quot;{0}&quot; as
        ///I=Information
        ///W=Warning
        ///E=Error
        ///Exception=Exception message: {0}
        ///Select_One=Select o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zelda Save Tool Translation File - español]
        ///Title=Conversor de guardados de OoT
        ///Drop_It=Arrastre su archivo de guardado aquí
        ///Supported=Formatos admitidos: {0}
        ///Version=Versión {0}
        ///Open_First=¡Abra primero un archivo de guardado!
        ///Supported_Filter=Todos los archivos admitidos|*.sra;*.sav;*.gci
        ///SRA_Filter=Archivos SRA (*.sra)|*.sra
        ///PC_Filter=Archivos de guardado de PC Port (*.sav)|*.sav
        ///GCI_Filter=Archivos GCI (*.gci)|*.gci
        ///All_Filter=Todos los archivos (*.*)|*.*
        ///Save_As_Title=Guardar &quot;{0}&quot; convertido como
        ///I=I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zelda Save Tool Translation File - français]
        ///Title=Convertisseur de sauvegarde OoT
        ///Drop_It=Déposez votre fichier de sauvegarde ici
        ///Supported=Formats pris en charge : {0}
        ///Version=Version {0}
        ///Open_First=Ouvrir d&apos;abord un fichier de sauvegarde !
        ///Supported_Filter=Tous les fichiers pris en charge|*.sra;*.sav;*.gci
        ///SRA_Filter=Fichiers SRA (*.sra)|*.sra
        ///PC_Filter=Fichiers de sauvegarde du port PC (*.sav)|*.sav
        ///GCI_Filter=Fichiers GCI (*.gci)|*.gci
        ///All_Filter=Tous les fichiers (*.*)|*.*
        ///Save_As_Title=Enregistrer &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Full {
            get {
                object obj = ResourceManager.GetObject("Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Half {
            get {
                object obj = ResourceManager.GetObject("Half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OneQuarter {
            get {
                object obj = ResourceManager.GetObject("OneQuarter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ThreeQuarter {
            get {
                object obj = ResourceManager.GetObject("ThreeQuarter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
